DjTodo/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
]

DjTodo/mysite/todo/urls.py
from django.urls import include, path
from . import views

app_name = 'todo'

urlpatterns = [
    path('vonly/', views.TodoVueOnlyTV.as_view(), name='vonly'),
    
    path('create/', views.TodoCreateView.as_view(), name='create'),
    path('list/', views.TodoListView.as_view(), name='list'),
    path('<int:pk>/delete/', views.TodoDeleteView.as_view(), name='delete'),
    
    path('mixin/', views.TodoMOMCV.as_view(), name='mixin'),
    path('<int:pk>/delete2/', views.TodoDelV2.as_view(), name='delete2'),
]

DjTodo/mysite/todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)
    
    def __str__(self):
        return self.todo
    
    def save(self):
        if not self.name:
            self.name = "devKya"
        super().save()

DjTodo/mysite/mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

DjTodo/mysite/todo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from .models import Todo
# Create your views here.
class TodoVueOnlyTV(TemplateView):
    template_name = 'todo/todo_vue_only.html'
    
    
class TodoCreateView(CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('todo:list')
    

class TodoListView(ListView):
    model = Todo
    template_name = 'todo/todo_list.html'
    
    
class TodoDeleteView(DeleteView):
    model = Todo
    template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:list')
    
    
class TodoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = '__all__'
    context_object_name = 'todo_list'
    template_name = 'todo/todo_form_list.html'
    success_url = reverse_lazy('todo:mixin')
    
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.todo_list = self.get_queryset()
        return super().post(request, *args, **kwargs)
    
    
class TodoDelV2(DeleteView):
    model = Todo
    # template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:mixin')
    
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)
    

DjTodo/mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <title>
      {% block title %}
        home.html
      {% endblock %}
    </title>
    <!-- CSS only -->
    <!-- bootstrap.css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
    <link rel="icon" href="{% static 'img/favicon.ico' %}"/>
    {% block extra-style %}{% endblock %}
    <!-- fontawesome.css -->
    <!-- favicon.ico -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">
          <b>ToDo</b>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:create' %}">DjangoOnly</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:vonly' %}">VueOnly</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:mixin' %}">DjangoMixin</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Util
              </a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
          <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1">
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                <i class="fa-solid fa-user"></i>&nbsp; DevKya &nbsp;</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                <a class="dropdown-item" href="{% url 'home' %}">Register</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}
    <!-- jquery.js popper.js bootstrap.js -->
    <script src="https://kit.fontawesome.com/b6d2927416.js" crossorigin="anonymous"></script>
    {% block extra-script %}{% endblock %}
  </body>

</html>

DjTodo/mysite/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
  <style type="text/css">
    .home-window {
      background-image: url("{% static 'img/vue.png' %}");
      background-repeat: no-repeat;
      background-position: center;
      background-size: 70%;
      height: 500px;
      border-top: 10px solid #ccc;
      border-bottom: 10px solid #ccc;
      color: yellow;
      padding: 20px 0 0 20px;
    }

    .title {
      color: #c80;
      font-weight: bold;
    }

    .powered {
      position: relative;
      top: 77%;
      color: #cc0;
      font-style: italic;
    }

    .footer-wrapper {
      background: #456;
      color: #eee;
      line-height: 50px;
    }

    .footer-wrapper a {
      color: #ff9;
      /* footer-right text */
    }

    .footer-wrapper a:hover {
      color: #0ff;
    }

    footer ul li {
      text-align: center;
    }
  </style>
{% endblock extra-style %}

{% block content %}
  <div class="home-window"></div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6">
      <h3>Todo App</h3>
      <p>With Todo app, you can manage, prioritize, and complete the most important things you need to do every day. I can focus on the most important things and I can do my day more deliberately. You can also share lists with colleagues, friends, and family.</p>
    </div>
    <div class="col-sm-6">
      <h3>Blog App</h3>
      <p>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc. A typical blog combines text, digital images, and links to other blogs, web pages, and other media related to its topic.</p>
    </div>
  </div>
{% endblock content %}

{% block footer %}
  <footer class="fixed-bottom footer-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <p>Copyright &copy; 2019 DjangoBook by shkim</p>
        </div>
        <div class="col-md-8">
          <ul class="list-inline float-right">
            <li class="list-inline-item">
              <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Introduction</a>
            </li>
            <li class="list-inline-item">
              <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Help</a>
            </li>
            <li class="list-inline-item">
              <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Something</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
{% endblock footer %}

{% block extra-script %}
  <script>
    $(function () {
      $('[data-toggle=tooltip]').tooltip();
    });
  </script>
{% endblock extra-script %}

DjTodo/mysite/todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}
{% block title %}todo_confirm_delete.html{% endblock title %}
{% block extra-style %}
  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }

    [v-cloak] {
      display: none;
    }
  </style>
{% endblock extra-style %}
{% block content %}
  <div id='app'>
    <h1>Todo Delete</h1>
    <strong>Are you sure to delete
      {{ object }}
      ?</strong>
    <br>
    <br>
    <form action="." method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger btn-sm">Yes</button>
    </form>
  </div>
{% endblock content %}

DjTodo/mysite/todo/templates/todo/todo_form.html
{% extends 'base.html' %}
{% block title %}todo_form.html{% endblock %}
{% block extra-style %}
  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 90px;
      padding-left: 20px;
      line-height: 10px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
      line-height: 10px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }

    [v-cloak] {
      display: none;
    }
  </style>
{% endblock %}
{% block content %}
  <div id="app">
    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br/>
    <br>

    <form class="inputBox" action="." method="post">
      {% csrf_token %}
      <input class="name" type="text" placeholder="name ..." name="name"/>
      <input class="item" type="text" placeholder="type anything welcomed ..." name="todo"/>
      <button type="submit" class="btn btn-secondary">ADD</button>
    </form>
  </div>
{% endblock %}

DjTodo/mysite/todo/templates/todo/todo_form_list.html
{% extends 'base.html' %}
{% block title %}todo_form.html{% endblock %}
{% block extra-style %}
  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 90px;
      padding-left: 20px;
      line-height: 10px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
      line-height: 10px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }

    [v-cloak] {
      display: none;
    }
  </style>
{% endblock %}
{% block content %}
  <div id="app">
    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br/>
    <br>

    <form class="inputBox" action="." method="post">
      {% csrf_token %}
      <input class="name" type="text" placeholder="name ..." name="name"/>
      <input class="item" type="text" placeholder="type anything welcomed ..." name="todo"/>
      <button type="submit" class="btn btn-secondary">ADD</button>
    </form>

    <ul class="todoList">
      {% for todo in todo_list %}
        <li>
          <span>{{todo.name}}:::
            {{todo.todo}}</span>
          <span class="removeBtn">
            <a href="{% url 'todo:delete2' todo.id %}">&#x00D7</a>
          </span>
        </li>
      {% endfor %}
    </ul>

  </div>
{% endblock %}

DjTodo/mysite/todo/templates/todo/todo_list.html
{% extends 'base.html' %}
{% block title %}todo_list.html{% endblock %}
{% block extra-style %}
  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }

    [v-cloak] {
      display: none;
    }
  </style>
{% endblock %}
{% block content %}
  <div id='app'>
    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br>

    <ul class="todoList">
      {% for todo in object_list %}
        <li>
          <span>{{todo.name}}:::
            {{todo.todo}}</span>
          <span class="removeBtn">
            <a href="{% url 'todo:delete' todo.id %}">&#x00D7</a>
          </span>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

DjTodo/mysite/todo/templates/todo/todo_vue_only.html
{% extends 'base.html' %}
{% block title %}todo_vue_only.html{% endblock title %}
{% block extra-style %}
  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
      line-height: 10px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
      line-height: 10px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }

    [v-cloak] {
      display: none;
    }
  </style>
{% endblock extra-style %}
{% block content %}
  <div id='app' v-cloak="v-cloak">

    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br>

    <div class="inputBox">
      <input class="name" type="text" placeholder="name ..." v-model.trim="name">
      <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="newTodoItem" @keyup.enter="add_todo">
      <button @click="add_todo">ADD</button>
    </div>

    <ul class="todoList">
      <li v-for="(todoItem, index) in todoItems">
        <span>{todoItem.name}::: {todoItem.item}</span>
        <span class="removeBtn" v-on:click.stop="remove_todo(todoItem, index)">&#x00D7</span>
      </li>
    </ul>

  </div>
{% endblock content %}
{% block extra-script %}
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script>
    var vm = new Vue({
      el: '#app',
      delimiters: [
        '{', '}'
      ],
      data: {
        name: '',
        newTodoItem: '',
        todoItems: [
          {
            name: '김석훈',
            item: 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'
          }, {
            name: '홍길동',
            item: '이름을 안쓰면 홍길동으로 나와요...'
          }, {
            name: '이순신',
            item: '신에게는 아직 열두 척의 배가 있사옵니다.'
          }, {
            name: '성춘향',
            item: '그네 타기'
          }
        ]
      },
      methods: {
        add_todo: function () {
          console.log('name:', this.name, this.newTodoItem);
          if (this.newTodoItem == '') 
            return;
          if (this.name == '') 
            this.name = '홍길동';
          
          this
            .todoItems
            .push({'name': this.name, 'item': this.newTodoItem});
          this.clear_input();
          // axios post
        },
        remove_todo: function (todoItem, index) {
          console.log(todoItem);
          this
            .todoItems
            .splice(index, 1);/* from index, count */
          // axios delete
        },
        clear_input: function () {
          this.name = '';
          this.newTodoItem = '';
        }
      }
    })
  </script>
{% endblock extra-script %}